apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: <NS_NAME>
spec:
  replicas: <RS>
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/prometheus"
    spec:
      volumes:
      - name: logs-volume
        hostPath:
          path: /opt/logs/<NS_NAME>/<APP_NAME>
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: config-volume
        configMap:
          name: <NGX-CONF>
      containers:
      - name: <APP_NAME>
        image: <HARBOR_ADDR>/<NS_NAME>/<APP_NAME>:<BUILD_TAG>
        imagePullPolicy: Always
        resources:
          limits:
            memory: <MEM>
            cpu: <CPU>
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d/
          - name: logs-volume
            mountPath: /var/log/nginx/
          - name: host-time
            mountPath: /etc/localtime
            readOnly: true
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: <HARBOR_SECRET>
